[package]
name = "blockchain-tutorial-part-2"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
num-bigint = "0.3.0"
num-traits = "0.2.12"
rust-crypto = "0.2.36"
